<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Kloos Calendar             |
 |                                                                       |
  |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://github.com/julianomeinen/kloos_calendar
*/

$labels = [];
$labels['button_label'] = 'Calendar';
$labels['page_title'] = 'Calendar';
$labels['weekday_1'] = 'Sunday';
$labels['weekday_2'] = 'Monday';
$labels['weekday_3'] = 'Tuesday';
$labels['weekday_4'] = 'Wednesday';
$labels['weekday_5'] = 'Thursday';
$labels['weekday_6'] = 'Friday';
$labels['weekday_7'] = 'Saturday';

$messages = [];
