<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Kloos Calendar             |
 |                                                                       |
  |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://github.com/julianomeinen/kloos_calendar
*/

$labels = [];
$labels['button_label'] = 'Calendário';
$labels['page_title'] = 'Calendário';
$labels['weekday_1'] = 'Domingo';
$labels['weekday_2'] = 'Segunda';
$labels['weekday_3'] = 'Terça';
$labels['weekday_4'] = 'Quarta';
$labels['weekday_5'] = 'Quinta';
$labels['weekday_6'] = 'Sexta';
$labels['weekday_7'] = 'Sábado';
$labels['date_format'] = 'd/m/Y';
$labels['welcome_message'] = 'Olá <strong>%s</strong>, hoje é %s, %s.';

$messages = [];
