<?php

/*
 +-----------------------------------------------------------------------+
 | Localization file of the Roundcube Webmail Kloos Calendar             |
 |                                                                       |
  |                                                                       |
 | Licensed under the GNU General Public License version 3 or            |
 | any later version with exceptions for skins & plugins.                |
 | See the README file for a full license statement.                     |
 +-----------------------------------------------------------------------+

 For translation see https://github.com/julianomeinen/kloos_calendar
*/

$labels = [];
$labels['button_label'] = 'Calendário';

$messages = [];
